### ISSUE TITLE
Test/Bundle Home cannot be set by external batch file

### ISSUE THREAD

**Issue by pbaumann88** [antoinewaugh/aunit#1]
Hi,

following problem occurs with the aunit.bat file:
When I call aunit.bat from an external batch file in which I set AUNIT_TEST_HOME and AUNIT_BUNDLE_HOME, I get the following error during execution:

"\Jenkins\workspace\AUNIT\.__test" kann syntaktisch an dieser Stelle nicht verarbeitet werden.

which translates to that "\Jenkins\workspace\AUNIT\.__test" cannot be syntactically processed on this position. What fixes the problem for me is:

replacing:

```
IF "%AUNIT_TEST_HOME%"=="" (
	SET AUNIT_TEST_HOME=%AUNIT_HOME%\.__test
)

IF "%AUNIT_BUNDLE_HOME%"=="" (
	SET AUNIT_BUNDLE_HOME=%AUNIT_HOME%\.__repository
)
```

with:

```
IF "%AUNIT_TEST_HOME%"=="" (
	SET "AUNIT_TEST_HOME=%AUNIT_HOME%\.__test"
)

IF "%AUNIT_BUNDLE_HOME%"=="" (
	SET "AUNIT_BUNDLE_HOME=%AUNIT_HOME%\.__repository"
)
```

Could you include this fix into your master branch? I'm using aunit with jenkins and need to run it via external batch file.
Thanks in advance!

**Comment by antoinewaugh** [comment]
Hello,

this issue has been patched. please do a git pull or clone.

thanks

antoine

**Comment by pbaumann88** [comment]
perfect, thank you :)

**Comment by antoinewaugh** [comment]
You're most welcome.

I hope you find aunit helpful.

Antoine

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
